#!/bin/bash

# Debian 12/13 amd64 initialization (single flow, no modes)
# - Performs environment detection, optional installs, timezone confirmation, and kernel tuning
# - Backs up configs to /root/.init_linux_backups where applicable (only if changed)

set -euo pipefail

export DEBIAN_FRONTEND=noninteractive

MARKER_FILE="/var/lib/init_linux_run.marker"
BACKUP_DIR="/root/.init_linux_backups"
SYSCTL_NETWORK_FILE="/etc/sysctl.d/99-network-tuning.conf"
SYSCTL_SWAPPINESS_FILE="/etc/sysctl.d/99-swappiness.conf"
SYSCTL_FORWARDING_FILE="/etc/sysctl.d/99-ip-forwarding.conf"
SYSCTL_IPV6_FILE="/etc/sysctl.d/99-ipv6-disable.conf"
MODE_LITE=0
GITHUB_ALLOWED=1
ENABLE_FORWARDING=0
DISABLE_IPV6=0
DOCKER_STATUS="unknown"
APT_INSTALL_OPTS="-y -qq -o=Dpkg::Use-Pty=0"
EXISTING_SYSCTL_SETTINGS=""
OTHER_SYSCTL_FILES=""
SCRIPT_TIMESTAMP=$(TZ=UTC date '+%Y%m%d-%H%M')

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
WHITE='\033[1;37m'
BOLD='\033[1m'
DIM='\033[2m'
RESET='\033[0m'

# Icons
ICON_INFO="ℹ️ "
ICON_WARN="⚠️ "
ICON_ERR="❌ "
ICON_OK="✓ "
ICON_PKG="📦 "
ICON_GEAR="⚙️ "
ICON_TIME="🕐 "
ICON_SEARCH="🔍 "
ICON_DOC="📜 "
ICON_TOOL="🧰 "

clear
echo ""
echo -e "${BLUE}"
cat << 'EOF'
 ____       _     _              ___       _ _   
|  _ \  ___| |__ (_) __ _ _ __  |_ _|_ __ (_) |_ 
| | | |/ _ \ '_ \| |/ _` | '_ \  | || '_ \| | __|
| |_| |  __/ |_) | | (_| | | | | | || | | | | |_ 
|____/ \___|_.__/|_|\__,_|_| |_|___|_| |_|_|\__|
EOF
echo -e "${RESET}"

print_banner() {
    echo ""
    echo -e "${BLUE}╭──────────────────────────────────────────────────────────────────────────────╮${RESET}"
    echo -e "${BLUE}│${RESET} ${BOLD}$1${RESET}"
    echo -e "${BLUE}╰──────────────────────────────────────────────────────────────────────────────╯${RESET}"
}

print_success() { echo -e "${GREEN}${ICON_OK} $1${RESET}"; }
print_warning() { echo -e "${YELLOW}${ICON_WARN} $1${RESET}"; }
print_error()   { echo -e "${RED}${ICON_ERR} $1${RESET}"; }
print_info()    { echo -e "${CYAN}${ICON_INFO} $1${RESET}"; }

print_kv() {
    local key="$1"
    local val="$2"
    printf "${DIM}%-22s${RESET} : %b\n" "$key" "$val"
}

require_root() {
    if [ "$(id -u)" -ne 0 ]; then
        print_error "Root privileges required. Please run with sudo."
        exit 1
    fi
}

detect_existing_sysctl() {
    EXISTING_SYSCTL_SETTINGS=""
    local found_files=""
    local script_files=""
    local other_files=""
    local key_settings=""
    local script_marker="Generated by: debian_init.sh"
    
    # Check /etc/sysctl.conf
    if [ -f /etc/sysctl.conf ]; then
        local conf_settings
        conf_settings=$(grep -v '^#' /etc/sysctl.conf 2>/dev/null | grep -v '^$' | grep '=' || true)
        if [ -n "$conf_settings" ]; then
            found_files="${found_files}/etc/sysctl.conf "
            other_files="${other_files}/etc/sysctl.conf "
            key_settings="${key_settings}${conf_settings}\n"
        fi
    fi
    
    # Check /etc/sysctl.d/*.conf
    if [ -d /etc/sysctl.d ]; then
        for f in /etc/sysctl.d/*.conf; do
            [ -f "$f" ] || continue
            local file_settings
            file_settings=$(grep -v '^#' "$f" 2>/dev/null | grep -v '^$' | grep '=' || true)
            if [ -n "$file_settings" ]; then
                found_files="${found_files}${f} "
                # Check if this file was generated by our script
                if grep -q "$script_marker" "$f" 2>/dev/null; then
                    script_files="${script_files}${f} "
                else
                    other_files="${other_files}${f} "
                fi
                key_settings="${key_settings}${file_settings}\n"
            fi
        done
    fi
    
    if [ -n "$found_files" ]; then
        EXISTING_SYSCTL_SETTINGS="$key_settings"
        OTHER_SYSCTL_FILES="$other_files"
        print_banner "${ICON_GEAR} Existing sysctl configurations detected"
        
        # Show script-generated files
        if [ -n "$script_files" ]; then
            print_info "Generated by this script:"
            for f in $script_files; do
                echo -e "  ${GREEN}•${RESET} $f"
            done
        fi
        
        # Show other files
        if [ -n "$other_files" ]; then
            print_info "Other configurations:"
            for f in $other_files; do
                echo -e "  ${BLUE}•${RESET} $f"
            done
        fi
        
        echo ""
        print_info "Key settings currently active:"
        
        # Show important network/kernel settings
        local bbr_set qdisc_set forward_set
        bbr_set=$(echo -e "$key_settings" | grep -E 'tcp_congestion_control|tcp_bbr' | head -n3 || true)
        qdisc_set=$(echo -e "$key_settings" | grep -E 'default_qdisc' | head -n1 || true)
        forward_set=$(echo -e "$key_settings" | grep -E 'ip_forward|forwarding' | head -n3 || true)
        
        [ -n "$bbr_set" ] && echo -e "  ${GREEN}TCP Congestion:${RESET}\n$(echo "$bbr_set" | sed 's/^/    /')"
        [ -n "$qdisc_set" ] && echo -e "  ${GREEN}Queue Discipline:${RESET}\n$(echo "$qdisc_set" | sed 's/^/    /')"
        [ -n "$forward_set" ] && echo -e "  ${GREEN}IP Forwarding:${RESET}\n$(echo "$forward_set" | sed 's/^/    /')"
        
        # Count total settings
        local total_count
        total_count=$(echo -e "$key_settings" | grep -c '=' || echo 0)
        print_kv "Total settings" "$total_count parameters configured"
        echo ""
    fi
}

check_marker() {
    if [ -f "$MARKER_FILE" ]; then
        MODE_LITE=1
        print_warning "Marker detected ($MARKER_FILE)."
        print_warning "Will run in re-run mode: update, tools, base packages, unattended-upgrades, Docker, zram, forwarding/IPv6."
        print_warning "Skipping: timezone, network-tuning."
    fi
}

require_debian() {
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        if [ "${ID:-}" != "debian" ]; then
            print_error "Debian only. Detected: ${PRETTY_NAME:-unknown}"
            exit 1
        fi
        DEBIAN_VERSION=$(cut -d. -f1 /etc/debian_version)
        if [ "$DEBIAN_VERSION" != "12" ] && [ "$DEBIAN_VERSION" != "13" ]; then
            print_error "Supported versions: Debian 12/13. Current: $DEBIAN_VERSION"
            exit 1
        fi
        ARCH=$(uname -m)
        if [ "$ARCH" != "x86_64" ] && [ "$ARCH" != "amd64" ]; then
            print_error "amd64 only. Current: $ARCH"
            exit 1
        fi
        DISTRO_CODENAME="${VERSION_CODENAME:-$(lsb_release -cs 2>/dev/null || echo trixie)}"
    else
        print_error "Cannot read /etc/os-release. Aborting."
        exit 1
    fi
}

backup_file() {
    local file="$1"
    local new_content="${2:-}"
    [ -f "$file" ] || return 0
    
    # If new content provided, compare with existing file
    if [ -n "$new_content" ]; then
        local current_content
        # Extract non-comment, non-empty lines for comparison
        current_content=$(grep -v '^#' "$file" 2>/dev/null | grep -v '^$' | sort || true)
        local new_clean
        new_clean=$(echo "$new_content" | grep -v '^#' | grep -v '^$' | sort || true)
        if [ "$current_content" = "$new_clean" ]; then
            # Content unchanged, skip backup
            return 0
        fi
    fi
    
    mkdir -p "$BACKUP_DIR"
    cp "$file" "${BACKUP_DIR}/$(basename "$file").$(date +%Y%m%d_%H%M%S).bak"
}

ensure_basic_tools() {
    print_banner "${ICON_PKG} Preparing prerequisites"
    apt-get update -qq >/dev/null 2>&1 || true
    apt-get install $APT_INSTALL_OPTS curl wget >/dev/null 2>&1 || true
    if ! command -v curl >/dev/null || ! command -v wget >/dev/null; then
        print_error "Failed to install curl or wget. Please check network or mirrors."
        exit 1
    fi
    print_success "Base utilities ready (curl, wget)"
}

fetch_ipinfo() {
    local raw
    raw=$(curl -s --max-time 5 ipinfo.io 2>/dev/null || true)
    IP_CITY=$(echo "$raw" | grep -oP '"city":\s*"\K[^"]+' || true)
    IP_REGION=$(echo "$raw" | grep -oP '"region":\s*"\K[^"]+' || true)
    IP_COUNTRY=$(echo "$raw" | grep -oP '"country":\s*"\K[^"]+' || true)
    IP_ORG=$(echo "$raw" | grep -oP '"org":\s*"\K[^"]+' || true)
    IP_TZ=$(echo "$raw" | grep -oP '"timezone":\s*"\K[^"]+' || true)
    IPV4_ADDR=$(curl -s --max-time 5 -4 ip.sb 2>/dev/null || echo "N/A")
    IPV6_ADDR=$(curl -s --max-time 5 -6 ip.sb 2>/dev/null || echo "N/A")
    
    # Detect IPv6 status: disabled by sysctl, no address assigned, or working
    IPV6_STATUS=""
    if [ "${IPV6_ADDR:-N/A}" = "N/A" ] || [ -z "$IPV6_ADDR" ]; then
        local ipv6_sysctl_disabled
        ipv6_sysctl_disabled=$(sysctl -n net.ipv6.conf.all.disable_ipv6 2>/dev/null || echo "0")
        if [ "$ipv6_sysctl_disabled" = "1" ]; then
            IPV6_STATUS="disabled by sysctl"
        else
            # Check if any interface has a global IPv6 address
            local has_ipv6_addr
            has_ipv6_addr=$(ip -6 addr show scope global 2>/dev/null | grep -c "inet6" || true)
            has_ipv6_addr=$(echo "$has_ipv6_addr" | tr -d '[:space:]')
            has_ipv6_addr=${has_ipv6_addr:-0}
            if [ "$has_ipv6_addr" -gt 0 ] 2>/dev/null; then
                IPV6_STATUS="address assigned but external unreachable"
            else
                IPV6_STATUS="not assigned by provider"
            fi
        fi
    fi

    # IPv6-only fallback: use ifconfig.co/json to populate IP and region fields
    if { [ -z "${IPV4_ADDR:-}" ] || [ "${IPV4_ADDR}" = "N/A" ]; } && [ "${IPV6_ADDR:-N/A}" != "N/A" ]; then
        local raw6
        raw6=$(curl -s --max-time 8 -6 ifconfig.co/json 2>/dev/null || true)
        if [ -n "$raw6" ]; then
            IPV6_ADDR=$(echo "$raw6" | grep -oP '"ip":\s*"\K[^"]+' || echo "$IPV6_ADDR")
            IP_CITY=$(echo "$raw6" | grep -oP '"city":\s*"\K[^"]+' || echo "${IP_CITY:-}")
            IP_REGION=$(echo "$raw6" | grep -oP '"region":\s*"\K[^"]+' || echo "${IP_REGION:-}")
            IP_COUNTRY=$(echo "$raw6" | grep -oP '"country_iso":\s*"\K[^"]+' || echo "${IP_COUNTRY:-}")
            if [ -z "$IP_COUNTRY" ]; then
                IP_COUNTRY=$(echo "$raw6" | grep -oP '"country":\s*"\K[^"]+' || echo "")
            fi
            IP_ORG=$(echo "$raw6" | grep -oP '"asn_org":\s*"\K[^"]+' || echo "${IP_ORG:-}")
            IP_TZ=$(echo "$raw6" | grep -oP '"time_zone":\s*"\K[^"]+' || echo "${IP_TZ:-}")
            if [ -z "$IP_TZ" ]; then
                IP_TZ=$(echo "$raw6" | grep -oP '"timezone":\s*"\K[^"]+' || echo "")
            fi
        fi
    fi

    # If no IPv4 is available, disable GitHub downloads to avoid failures on IPv6-only hosts.
    if [ -z "${IPV4_ADDR:-}" ] || [ "${IPV4_ADDR}" = "N/A" ]; then
        GITHUB_ALLOWED=0
    fi
}

command_exists() { command -v "$1" >/dev/null 2>&1; }

# Remove apt-installed package if exists (to install newer version from GitHub)
remove_apt_pkg() {
    local pkg="$1"
    if dpkg -l "$pkg" 2>/dev/null | grep -q "^ii"; then
        print_info "Removing apt-installed $pkg (will install newer version from GitHub)..."
        apt-get remove -y -qq "$pkg" 2>/dev/null || true
    fi
}

get_eza_version() {
    local out ver
    out=$(eza --version 2>/dev/null | head -n2)
    ver=$(echo "$out" | grep -Eo '[0-9]+(\.[0-9]+)+' | head -n1)
    echo "${ver:-unknown}"
}

get_helix_version() {
    local out ver
    out=$(hx --version 2>/dev/null | head -n1)
    ver=$(echo "$out" | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?' | head -n1)
    echo "${ver:-unknown}"
}

get_speedtest_version() {
    local out ver
    out=$(speedtest --version 2>/dev/null | head -n1)
    ver=$(echo "$out" | grep -oP '([0-9]+\.)+[0-9]+' | head -n1)
    echo "${ver:-unknown}"
}

get_duf_version() {
    local out ver
    out=$(duf --version 2>/dev/null | head -n1)
    ver=$(echo "$out" | grep -oE '[0-9]+(\.[0-9]+)+' | head -n1)
    echo "${ver:-unknown}"
}

get_bat_version() {
    local ver
    ver=$(bat --version 2>/dev/null | grep -oE '[0-9]+(\.[0-9]+)+' | head -n1)
    echo "${ver:-unknown}"
}

get_btop_version() {
    local ver
    ver=$(btop --version 2>/dev/null | grep -oE '[0-9]+(\.[0-9]+)+' | head -n1)
    echo "${ver:-unknown}"
}

get_fd_version() {
    local ver
    ver=$(fd --version 2>/dev/null | grep -oE '[0-9]+(\.[0-9]+)+' | head -n1)
    echo "${ver:-unknown}"
}

get_procs_version() {
    local ver
    ver=$(procs --version 2>/dev/null | grep -oE '[0-9]+(\.[0-9]+)+' | head -n1)
    echo "${ver:-unknown}"
}

get_tldr_version() {
    local ver
    ver=$(tldr --version 2>/dev/null | grep -oE '[0-9]+(\.[0-9]+)+' | head -n1)
    echo "${ver:-unknown}"
}

get_zoxide_version() {
    local ver
    ver=$(zoxide --version 2>/dev/null | grep -oE '[0-9]+(\.[0-9]+)+' | head -n1)
    echo "${ver:-unknown}"
}

get_gping_version() {
    local ver
    ver=$(gping --version 2>/dev/null | grep -oE '[0-9]+(\.[0-9]+)+' | head -n1)
    echo "${ver:-unknown}"
}

get_nexttrace_version() {
    local ver
    ver=$(nexttrace --version 2>/dev/null | grep -oE '[0-9]+(\.[0-9]+)+' | head -n1)
    echo "${ver:-unknown}"
}

detect_versions() {
    EZA_VER="Not installed"
    HELIX_VER="Not installed"
    SPEEDTEST_VER="Not installed"
    DUF_VER="Not installed"
    BAT_VER="Not installed"
    BTOP_VER="Not installed"
    FD_VER="Not installed"
    PROCS_VER="Not installed"
    TLDR_VER="Not installed"
    ZOXIDE_VER="Not installed"
    GPING_VER="Not installed"
    NEXTTRACE_VER="Not installed"
    AUTO_UPDATES="Not installed"

    if command_exists eza; then EZA_VER=$(get_eza_version); fi
    if command_exists hx; then HELIX_VER=$(get_helix_version); fi
    if command_exists speedtest; then SPEEDTEST_VER=$(get_speedtest_version); fi
    if command_exists duf; then DUF_VER=$(get_duf_version); fi
    if command_exists bat; then BAT_VER=$(get_bat_version); fi
    if command_exists btop; then BTOP_VER=$(get_btop_version); fi
    if command_exists fd; then FD_VER=$(get_fd_version); fi
    if command_exists procs; then PROCS_VER=$(get_procs_version); fi
    if command_exists tldr; then TLDR_VER=$(get_tldr_version); fi
    if command_exists zoxide; then ZOXIDE_VER=$(get_zoxide_version); fi
    if command_exists gping; then GPING_VER=$(get_gping_version); fi
    if command_exists nexttrace; then NEXTTRACE_VER=$(get_nexttrace_version); fi
    if command_exists unattended-upgrade; then AUTO_UPDATES="installed"; fi
}

detect_updates_hint() {
    # Temporarily disable pipefail for this function - empty API responses cause grep to fail
    set +o pipefail
    EZA_UPDATE=""
    HELIX_UPDATE=""
    SPEEDTEST_UPDATE=""
    DUF_UPDATE=""
    BAT_UPDATE=""
    BTOP_UPDATE=""
    FD_UPDATE=""
    PROCS_UPDATE=""
    TLDR_UPDATE=""
    ZOXIDE_UPDATE=""
    GPING_UPDATE=""
    NEXTTRACE_UPDATE=""

    if command_exists eza; then
        latest=$(curl -s --max-time 10 https://api.github.com/repos/eza-community/eza/releases/latest 2>/dev/null | grep '"tag_name":' | sed -E 's/.*"tag_name": "([^"]+)".*/\1/' || true)
        current=$(get_eza_version)
        latest_clean=$(echo "${latest#v}" | grep -Eo '[0-9]+(\.[0-9]+)+' | head -n1 || true)
        if [ -n "$latest_clean" ] && [ -n "$current" ] && [ "$latest_clean" != "$current" ]; then
            EZA_UPDATE="$current → $latest_clean"
        fi
    fi

    if command_exists hx; then
        latest=$(curl -s --max-time 10 https://api.github.com/repos/helix-editor/helix/releases/latest 2>/dev/null | grep '"tag_name":' | sed -E 's/.*"tag_name": "v?([^"]+)".*/\1/' || true)
        current=$(hx --version 2>/dev/null | grep -oE '[0-9]+(\.[0-9]+)+' | head -n1 || echo "")
        [ -n "$latest" ] && [ -n "$current" ] && [ "$latest" != "$current" ] && HELIX_UPDATE="$current → $latest"
    fi

    if command_exists speedtest; then
        latest=$(curl -sL "https://packagecloud.io/ookla/speedtest-cli/debian/dists/${DISTRO_CODENAME}/main/binary-amd64/Packages" 2>/dev/null | grep -A10 "Package: speedtest" | grep "^Version:" | head -n1 | awk '{print $2}' || true)
        current=$(get_speedtest_version)
        latest_num=$(echo "$latest" | cut -d- -f1)
        current_num=$(echo "$current" | cut -d- -f1)
        if [ -n "$latest_num" ] && [ -n "$current_num" ] && [ "$latest_num" != "$current_num" ]; then
            SPEEDTEST_UPDATE="$current_num → $latest"
        fi
    fi

    if command_exists duf; then
        latest=$(curl -s --max-time 10 https://api.github.com/repos/muesli/duf/releases/latest 2>/dev/null | grep '"tag_name":' | sed -E 's/.*"tag_name": "v?([^"]+)".*/\1/' || true)
        current=$(get_duf_version)
        if [ -n "$latest" ] && [ -n "$current" ] && [ "$latest" != "$current" ]; then
            DUF_UPDATE="$current → $latest"
        fi
    fi

    if command_exists bat; then
        latest=$(curl -s --max-time 10 https://api.github.com/repos/sharkdp/bat/releases/latest 2>/dev/null | grep '"tag_name":' | sed -E 's/.*"tag_name": "v?([^"]+)".*/\1/' || true)
        current=$(get_bat_version)
        [ -n "$latest" ] && [ -n "$current" ] && [ "$latest" != "$current" ] && BAT_UPDATE="$current → $latest"
    fi

    if command_exists btop; then
        latest=$(curl -s --max-time 10 https://api.github.com/repos/aristocratos/btop/releases/latest 2>/dev/null | grep '"tag_name":' | sed -E 's/.*"tag_name": "v?([^"]+)".*/\1/' || true)
        current=$(get_btop_version)
        [ -n "$latest" ] && [ -n "$current" ] && [ "$latest" != "$current" ] && BTOP_UPDATE="$current → $latest"
    fi

    if command_exists fd; then
        latest=$(curl -s --max-time 10 https://api.github.com/repos/sharkdp/fd/releases/latest 2>/dev/null | grep '"tag_name":' | sed -E 's/.*"tag_name": "v?([^"]+)".*/\1/' || true)
        current=$(get_fd_version)
        [ -n "$latest" ] && [ -n "$current" ] && [ "$latest" != "$current" ] && FD_UPDATE="$current → $latest"
    fi

    if command_exists procs; then
        latest=$(curl -s --max-time 10 https://api.github.com/repos/dalance/procs/releases/latest 2>/dev/null | grep '"tag_name":' | sed -E 's/.*"tag_name": "v?([^"]+)".*/\1/' || true)
        current=$(get_procs_version)
        [ -n "$latest" ] && [ -n "$current" ] && [ "$latest" != "$current" ] && PROCS_UPDATE="$current → $latest"
    fi

    if command_exists tldr; then
        latest=$(curl -sL --max-time 10 https://api.github.com/repos/tldr-pages/tlrc/releases/latest 2>/dev/null | grep '\"tag_name\":' | sed -E 's/.*\"tag_name\": \"v?([^\"]+)\".*/\1/' || true)
        current=$(get_tldr_version)
        [ -n "$latest" ] && [ -n "$current" ] && [ "$latest" != "$current" ] && TLDR_UPDATE="$current → $latest"
    fi

    if command_exists zoxide; then
        latest=$(curl -s --max-time 10 https://api.github.com/repos/ajeetdsouza/zoxide/releases/latest 2>/dev/null | grep '"tag_name":' | sed -E 's/.*"tag_name": "v?([^"]+)".*/\1/' || true)
        current=$(get_zoxide_version)
        [ -n "$latest" ] && [ -n "$current" ] && [ "$latest" != "$current" ] && ZOXIDE_UPDATE="$current → $latest"
    fi

    if command_exists gping; then
        latest=$(curl -s --max-time 10 https://api.github.com/repos/orf/gping/releases/latest 2>/dev/null | grep '"tag_name":' | sed -E 's/.*"tag_name": "gping-v?([^"]+)".*/\1/' || true)
        current=$(get_gping_version)
        [ -n "$latest" ] && [ -n "$current" ] && [ "$latest" != "$current" ] && GPING_UPDATE="$current → $latest"
    fi

    if command_exists nexttrace; then
        latest=$(curl -s --max-time 10 https://api.github.com/repos/nxtrace/NTrace-core/releases/latest 2>/dev/null | grep '"tag_name":' | sed -E 's/.*"tag_name": "v?([^"]+)".*/\1/' || true)
        current=$(get_nexttrace_version)
        [ -n "$latest" ] && [ -n "$current" ] && [ "$latest" != "$current" ] && NEXTTRACE_UPDATE="$current → $latest"
    fi
    # Restore pipefail
    set -o pipefail
}

detect_unattended() {
    UNATTENDED_STATUS="Not installed"
    UNATTENDED_SOURCES="N/A"
    UNATTENDED_TIMER="Inactive"
    local codename_regex
    codename_regex="(${DISTRO_CODENAME}|\\\${distro_codename})"
    if command_exists unattended-upgrade; then
        UNATTENDED_STATUS="Installed"
        cfg=""
        if [ -f /etc/apt/apt.conf.d/52unattended-upgrades-local ]; then
            cfg="/etc/apt/apt.conf.d/52unattended-upgrades-local"
        elif [ -f /etc/apt/apt.conf.d/50unattended-upgrades ]; then
            cfg="/etc/apt/apt.conf.d/50unattended-upgrades"
        fi
        if [ -n "$cfg" ]; then
            sec=""
            upd=""
            if grep -qE "^\\s*\\\"origin=Debian,codename=${codename_regex}-security" "$cfg" 2>/dev/null; then
                sec="Security"
            fi
            if grep -qE "^\\s*\\\"origin=Debian,codename=${codename_regex}-updates" "$cfg" 2>/dev/null; then
                upd="Stable-updates"
            fi
            tmp="${sec}${sec:+ }${upd}"
            UNATTENDED_SOURCES=${tmp:-unknown}
        fi
        UNATTENDED_TIMER=$(systemctl is-active apt-daily-upgrade.timer 2>/dev/null || echo "Inactive")
    fi
}

# Memory tier labels removed - unified kernel parameters for all memory sizes

detect_system() {
    MEM_KB=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
    SWAP_KB=$(awk '/SwapTotal/ {print $2}' /proc/meminfo)
    DISK_ROOT=$(df -h / | awk 'NR==2{print $3 " / " $2 " (" $5 " used)"}')
    BBR_STATUS=$(sysctl -n net.ipv4.tcp_congestion_control 2>/dev/null || echo "unknown")
    QDISC_STATUS=$(sysctl -n net.core.default_qdisc 2>/dev/null || echo "unknown")
    SWAP_STR="Not enabled"
    if [ "${SWAP_KB:-0}" -gt 0 ]; then
        SWAP_STR="$(awk '/SwapTotal/ {printf "%.1f MB", $2/1024}' /proc/meminfo)"
    fi
}

detect_docker_status() {
    if command_exists docker; then
        DOCKER_STATUS=$(docker --version 2>/dev/null | head -n1 || echo "installed")
    else
        DOCKER_STATUS="Not installed"
    fi
}

detect_zram_status() {
    ZRAM_STATUS="Not active"
    if grep -q "^/dev/zram" /proc/swaps 2>/dev/null; then
        local size_kb prio
        size_kb=$(awk '$1 ~ /zram/ {s+=$3} END {print s+0}' /proc/swaps)
        prio=$(awk '$1 ~ /zram/ {print $5; exit}' /proc/swaps)
        if [ "${size_kb:-0}" -gt 0 ]; then
            ZRAM_STATUS=$(awk -v s="$size_kb" -v p="$prio" 'BEGIN {printf "Active (%.1f MB, prio %s)", s/1024, p}')
        else
            ZRAM_STATUS="Active (size unknown, prio ${prio:-?})"
        fi
    fi
}

show_detection() {
    print_banner "${ICON_SEARCH} Environment check"
    print_kv "IPv4" "${IPV4_ADDR:-N/A}"
    if [ "${IPV6_ADDR:-N/A}" != "N/A" ] && [ -n "$IPV6_ADDR" ]; then
        print_kv "IPv6" "$IPV6_ADDR"
    elif [ -n "$IPV6_STATUS" ]; then
        print_kv "IPv6" "${YELLOW}Not available${RESET} (${IPV6_STATUS})"
    else
        print_kv "IPv6" "N/A"
    fi
    print_kv "ASN" "${IP_ORG:-?}"
    print_kv "Location" "${IP_CITY:-?}, ${IP_REGION:-?}, ${IP_COUNTRY:-?}"
    CURRENT_TZ_DISPLAY=$(timedatectl show --property=Timezone --value 2>/dev/null || echo "Unknown")
    print_kv "Timezone" "${CURRENT_TZ_DISPLAY}"
    print_kv "CPU" "$(lscpu 2>/dev/null | grep 'Model name' | cut -d: -f2- | xargs || echo '?')"
    print_kv "Memory" "$(echo "$MEM_KB" | awk '{printf "%.1f MB", $1/1024}')"
    print_kv "Swap" "$SWAP_STR"
    print_kv "zram swap" "${ZRAM_STATUS:-not detected}"
    print_kv "Disk (/)" "$DISK_ROOT"
    print_kv "BBR / qdisc" "$BBR_STATUS / $QDISC_STATUS"
    echo ""
    print_info "Modern CLI tools:"
    print_kv "  Eza" "$EZA_VER"
    print_kv "  Helix" "$HELIX_VER"
    print_kv "  Bat" "$BAT_VER"
    print_kv "  Btop" "$BTOP_VER"
    print_kv "  Duf" "$DUF_VER"
    print_kv "  Fd" "$FD_VER"
    print_kv "  Procs" "$PROCS_VER"
    print_kv "  Tldr" "$TLDR_VER"
    print_kv "  Zoxide" "$ZOXIDE_VER"
    print_kv "  Gping" "$GPING_VER"
    print_kv "  Speedtest" "$SPEEDTEST_VER"
    echo ""
    print_kv "Nexttrace" "$NEXTTRACE_VER"
    print_kv "Docker" "$DOCKER_STATUS"
    print_kv "Unattended-Upgrades" "$UNATTENDED_STATUS (sources: $UNATTENDED_SOURCES, timer: $UNATTENDED_TIMER)"
    
    local all_updates="$EZA_UPDATE$HELIX_UPDATE$SPEEDTEST_UPDATE$DUF_UPDATE$BAT_UPDATE$BTOP_UPDATE$FD_UPDATE$PROCS_UPDATE$TLDR_UPDATE$ZOXIDE_UPDATE$GPING_UPDATE$NEXTTRACE_UPDATE"
    if [ -n "$all_updates" ]; then
        echo ""
        print_warning "Updates available:"
        [ -n "$EZA_UPDATE" ] && echo -e "  ${YELLOW}•${RESET} Eza $EZA_UPDATE"
        [ -n "$HELIX_UPDATE" ] && echo -e "  ${YELLOW}•${RESET} Helix $HELIX_UPDATE"
        [ -n "$BAT_UPDATE" ] && echo -e "  ${YELLOW}•${RESET} Bat $BAT_UPDATE"
        [ -n "$BTOP_UPDATE" ] && echo -e "  ${YELLOW}•${RESET} Btop $BTOP_UPDATE"
        [ -n "$DUF_UPDATE" ] && echo -e "  ${YELLOW}•${RESET} Duf $DUF_UPDATE"
        [ -n "$FD_UPDATE" ] && echo -e "  ${YELLOW}•${RESET} Fd $FD_UPDATE"
        [ -n "$PROCS_UPDATE" ] && echo -e "  ${YELLOW}•${RESET} Procs $PROCS_UPDATE"
        [ -n "$TLDR_UPDATE" ] && echo -e "  ${YELLOW}•${RESET} Tldr $TLDR_UPDATE"
        [ -n "$ZOXIDE_UPDATE" ] && echo -e "  ${YELLOW}•${RESET} Zoxide $ZOXIDE_UPDATE"
        [ -n "$GPING_UPDATE" ] && echo -e "  ${YELLOW}•${RESET} Gping $GPING_UPDATE"
        [ -n "$SPEEDTEST_UPDATE" ] && echo -e "  ${YELLOW}•${RESET} Speedtest $SPEEDTEST_UPDATE"
        [ -n "$NEXTTRACE_UPDATE" ] && echo -e "  ${YELLOW}•${RESET} Nexttrace $NEXTTRACE_UPDATE"
    fi
}

confirm_proceed() {
    echo ""
    print_banner "${ICON_DOC} Planned actions"
    if [ "$MODE_LITE" -eq 1 ]; then
        echo -e " ${BLUE}1)${RESET} Update/upgrade/autoremove"
        echo -e " ${BLUE}2)${RESET} Modern CLI tools"
        echo -e " ${BLUE}3)${RESET} unattended-upgrades: configure"
        echo -e " ${BLUE}4)${RESET} Docker + Nexttrace: install prompts"
        echo -e " ${BLUE}5)${RESET} zram swap: configure or adjust"
        echo -e " ${BLUE}6)${RESET} IP forwarding / IPv6: configure"
    else
        echo -e " ${BLUE}1)${RESET} Update/upgrade/autoremove"
        echo -e " ${BLUE}2)${RESET} Modern CLI tools"
        echo -e " ${BLUE}3)${RESET} Docker + Nexttrace: install prompts"
        echo -e " ${BLUE}4)${RESET} Base packages (chrony, fail2ban, vnstat, etc.)"
        echo -e " ${BLUE}5)${RESET} Time sync/timezone; zram swap"
        echo -e " ${BLUE}6)${RESET} Network tuning: BBR + TCP optimization + security hardening"
        echo -e " ${BLUE}7)${RESET} IP forwarding / IPv6: configure"
    fi
    echo ""
    echo -ne "${BOLD}Proceed? [Y/n]: ${RESET}"
    read -r ans
    ans=${ans:-y}
    if [[ ! "$ans" =~ ^[Yy]$ ]]; then
        print_warning "Cancelled by user."
        exit 0
    fi
}

apt_refresh() {
    print_banner "${ICON_PKG} System update"
    apt-get update -qq
    apt-get upgrade $APT_INSTALL_OPTS
    apt-get autoremove $APT_INSTALL_OPTS
    print_success "System update completed"
}

install_unattended() {
    print_info "Installing unattended-upgrades..."
    apt-get install $APT_INSTALL_OPTS unattended-upgrades
    echo unattended-upgrades unattended-upgrades/enable_auto_updates boolean true | debconf-set-selections
    dpkg-reconfigure -f noninteractive unattended-upgrades
}

install_speedtest() {
    if command_exists speedtest; then
        print_info "Speedtest already installed, skipping."
        return
    fi
    print_info "Installing Speedtest..."
    pkg_path=$(curl -sL "https://packagecloud.io/ookla/speedtest-cli/debian/dists/${DISTRO_CODENAME}/main/binary-amd64/Packages" 2>/dev/null | grep -A10 "Package: speedtest" | grep "^Filename:" | head -n1 | awk '{print $2}' || true)
    if [ -z "$pkg_path" ]; then print_error "Unable to get Speedtest package path"; return; fi
    url="https://packagecloud.io/ookla/speedtest-cli/debian/${pkg_path}"
    wget -q "$url" -O /tmp/speedtest.deb
    if [ -s /tmp/speedtest.deb ]; then
        dpkg -i /tmp/speedtest.deb || apt-get install -f $APT_INSTALL_OPTS
        rm -f /tmp/speedtest.deb
        print_success "Speedtest installed"
    else
        print_error "Failed to download Speedtest"
    fi
}

install_helix() {
    if [ "$GITHUB_ALLOWED" -eq 0 ]; then
        print_warning "IPv6-only detected: skipping Helix (GitHub download required)."
        return
    fi
    if command_exists hx; then
        print_info "Helix already installed, skipping."
        return
    fi
    print_info "Installing Helix..."
    url=$(curl -s --max-time 10 https://api.github.com/repos/helix-editor/helix/releases/latest 2>/dev/null | grep -m1 '"browser_download_url".*amd64\.deb"' | cut -d'"' -f4 || true)
    if [ -z "$url" ]; then print_error "Failed to fetch Helix release"; return; fi
    wget -q "$url" -O /tmp/helix.deb
    if dpkg -i /tmp/helix.deb 2>/dev/null; then
        apt-get install -f $APT_INSTALL_OPTS
        cat > /etc/profile.d/helix-alias.sh <<'EOF'
alias vi='hx'
alias vim='hx'
EOF
        chmod 644 /etc/profile.d/helix-alias.sh
        # Source aliases in current shell
        source /etc/profile.d/helix-alias.sh 2>/dev/null || true
        print_success "Helix installed (aliases: vi, vim, hx)"
    else
        print_error "Helix installation failed"
    fi
    rm -f /tmp/helix.deb
}

install_eza() {
    if [ "$GITHUB_ALLOWED" -eq 0 ]; then
        print_warning "IPv6-only detected: skipping Eza (GitHub download required)."
        return
    fi
    if command_exists eza; then
        print_info "Eza already installed, skipping."
        return
    fi
    print_info "Installing Eza..."
    url=$(curl -s --max-time 10 https://api.github.com/repos/eza-community/eza/releases/latest 2>/dev/null | grep -m1 '"browser_download_url".*eza_x86_64-unknown-linux-gnu.tar.gz"' | cut -d'"' -f4 || true)
    if [ -z "$url" ]; then print_error "Failed to fetch Eza release"; return; fi
    wget -q "$url" -O /tmp/eza.tar.gz
    tmpdir=$(mktemp -d)
    if tar -xzf /tmp/eza.tar.gz -C "$tmpdir" 2>/dev/null; then
        binpath=$(find "$tmpdir" -type f -name eza -executable -print -quit 2>/dev/null || true)
        if [ -n "$binpath" ]; then
            install -m 755 "$binpath" /usr/local/bin/eza
            cat > /etc/profile.d/eza-alias.sh <<'EOF'
alias ls='eza'
alias ll='eza -lh --icons --git'
alias la='eza -lah --icons --git'
alias lt='eza -lh --icons --git --tree'
alias l='eza -lah --icons --git'
EOF
            chmod 644 /etc/profile.d/eza-alias.sh
            # Source aliases in current shell
            source /etc/profile.d/eza-alias.sh 2>/dev/null || true
            print_success "Eza installed (aliases: ls, ll, la, lt, l)"
        else
            print_error "Eza binary not found in archive"
        fi
    else
        print_error "Failed to extract Eza archive"
    fi
    rm -rf "$tmpdir" /tmp/eza.tar.gz
}

install_duf() {
    if [ "$GITHUB_ALLOWED" -eq 0 ]; then
        print_warning "IPv6-only detected: skipping Duf (GitHub download required)."
        return
    fi
    if command_exists duf; then
        print_info "Duf already installed, skipping."
        return
    fi
    print_info "Installing Duf..."
    # Get latest version tag from GitHub API
    latest_tag=$(curl -s --max-time 10 https://api.github.com/repos/muesli/duf/releases/latest 2>/dev/null | grep '"tag_name":' | sed -E 's/.*"tag_name": "([^"]+)".*/\1/' || true)
    if [ -z "$latest_tag" ]; then print_error "Failed to fetch Duf release info"; return; fi
    # Construct download URL: https://github.com/muesli/duf/releases/download/v0.9.1/duf_0.9.1_linux_x86_64.tar.gz
    version_num="${latest_tag#v}"
    url="https://github.com/muesli/duf/releases/download/${latest_tag}/duf_${version_num}_linux_x86_64.tar.gz"
    wget -q "$url" -O /tmp/duf.tar.gz
    tmpdir=$(mktemp -d)
    if tar -xzf /tmp/duf.tar.gz -C "$tmpdir" 2>/dev/null; then
        binpath=$(find "$tmpdir" -type f -name duf -executable -print -quit 2>/dev/null || true)
        if [ -n "$binpath" ]; then
            install -m 755 "$binpath" /usr/local/bin/duf
            cat > /etc/profile.d/duf-alias.sh <<'EOF'
alias df='duf'
EOF
            chmod 644 /etc/profile.d/duf-alias.sh
            # Source alias in current shell
            source /etc/profile.d/duf-alias.sh 2>/dev/null || true
            print_success "Duf installed (alias: df)"
        else
            print_error "Duf binary not found in archive"
        fi
    else
        print_error "Failed to extract Duf archive"
    fi
    rm -rf "$tmpdir" /tmp/duf.tar.gz
}

install_bat() {
    if [ "$GITHUB_ALLOWED" -eq 0 ]; then
        print_warning "IPv6-only detected: skipping Bat (GitHub download required)."
        return
    fi
    # Remove apt version if exists
    remove_apt_pkg bat
    if command_exists bat; then
        print_info "Bat already installed, skipping."
        return
    fi
    print_info "Installing Bat..."
    # Get latest .deb from GitHub
    url=$(curl -s --max-time 10 https://api.github.com/repos/sharkdp/bat/releases/latest 2>/dev/null | grep -m1 '"browser_download_url".*bat_.*_amd64\.deb"' | cut -d'"' -f4 || true)
    if [ -z "$url" ]; then print_error "Failed to fetch Bat release"; return; fi
    wget -q "$url" -O /tmp/bat.deb
    if dpkg -i /tmp/bat.deb 2>/dev/null; then
        apt-get install -f $APT_INSTALL_OPTS 2>/dev/null || true
        cat > /etc/profile.d/bat-alias.sh <<'EOF'
alias cat='bat --paging=never'
alias less='bat --paging=always'
EOF
        chmod 644 /etc/profile.d/bat-alias.sh
        print_success "Bat installed (aliases: cat, less)"
    else
        print_error "Bat installation failed"
    fi
    rm -f /tmp/bat.deb
}

install_btop() {
    if [ "$GITHUB_ALLOWED" -eq 0 ]; then
        print_warning "IPv6-only detected: skipping Btop (GitHub download required)."
        return
    fi
    # Remove apt version if exists
    remove_apt_pkg btop
    if command_exists btop; then
        print_info "Btop already installed, skipping."
        return
    fi
    # Ensure bzip2 is installed for .tbz extraction
    if ! command_exists bzip2; then
        apt-get install -qq -y bzip2 >/dev/null 2>&1
    fi
    print_info "Installing Btop..."
    # Get latest release tarball
    url=$(curl -s --max-time 10 https://api.github.com/repos/aristocratos/btop/releases/latest 2>/dev/null | grep -m1 '"browser_download_url".*btop-x86_64-linux-musl\.tbz"' | cut -d'"' -f4 || true)
    if [ -z "$url" ]; then print_error "Failed to fetch Btop release"; return; fi
    wget -q "$url" -O /tmp/btop.tbz
    tmpdir=$(mktemp -d)
    if tar -xjf /tmp/btop.tbz -C "$tmpdir" 2>/dev/null; then
        # Run the install script in btop directory with --prefix
        if [ -f "$tmpdir/btop/install.sh" ]; then
            cd "$tmpdir/btop" && ./install.sh --prefix /usr/local </dev/null >/dev/null 2>&1 || true
            cd - >/dev/null
            cat > /etc/profile.d/btop-alias.sh <<'EOF'
alias htop='btop'
alias top='btop'
EOF
            chmod 644 /etc/profile.d/btop-alias.sh
            print_success "Btop installed (aliases: htop, top)"
        elif [ -f "$tmpdir/btop/bin/btop" ]; then
            install -m 755 "$tmpdir/btop/bin/btop" /usr/local/bin/btop
            cat > /etc/profile.d/btop-alias.sh <<'EOF'
alias htop='btop'
alias top='btop'
EOF
            chmod 644 /etc/profile.d/btop-alias.sh
            print_success "Btop installed (aliases: htop, top)"
        else
            print_error "Btop binary not found in archive"
        fi
    else
        print_error "Failed to extract Btop archive"
    fi
    rm -rf "$tmpdir" /tmp/btop.tbz
}

install_fd() {
    if [ "$GITHUB_ALLOWED" -eq 0 ]; then
        print_warning "IPv6-only detected: skipping Fd (GitHub download required)."
        return
    fi
    # Remove apt version if exists
    remove_apt_pkg fd-find
    if command_exists fd; then
        print_info "Fd already installed, skipping."
        return
    fi
    print_info "Installing Fd..."
    # Get latest .deb from GitHub
    url=$(curl -s --max-time 10 https://api.github.com/repos/sharkdp/fd/releases/latest 2>/dev/null | grep -m1 '"browser_download_url".*fd_.*_amd64\.deb"' | cut -d'"' -f4 || true)
    if [ -z "$url" ]; then print_error "Failed to fetch Fd release"; return; fi
    wget -q "$url" -O /tmp/fd.deb
    if dpkg -i /tmp/fd.deb 2>/dev/null; then
        apt-get install -f $APT_INSTALL_OPTS 2>/dev/null || true
        cat > /etc/profile.d/fd-alias.sh <<'EOF'
alias find='fd'
EOF
        chmod 644 /etc/profile.d/fd-alias.sh
        print_success "Fd installed (alias: find)"
    else
        print_error "Fd installation failed"
    fi
    rm -f /tmp/fd.deb
}

install_procs() {
    if [ "$GITHUB_ALLOWED" -eq 0 ]; then
        print_warning "IPv6-only detected: skipping Procs (GitHub download required)."
        return
    fi
    if command_exists procs; then
        print_info "Procs already installed, skipping."
        return
    fi
    print_info "Installing Procs..."
    # Get latest release binary
    url=$(curl -s --max-time 10 https://api.github.com/repos/dalance/procs/releases/latest 2>/dev/null | grep -m1 '"browser_download_url".*procs-.*-x86_64-linux\.zip"' | cut -d'"' -f4 || true)
    if [ -z "$url" ]; then print_error "Failed to fetch Procs release"; return; fi
    wget -q "$url" -O /tmp/procs.zip
    tmpdir=$(mktemp -d)
    if unzip -q /tmp/procs.zip -d "$tmpdir" 2>/dev/null; then
        binpath=$(find "$tmpdir" -type f -name procs -executable -print -quit 2>/dev/null || true)
        if [ -n "$binpath" ]; then
            install -m 755 "$binpath" /usr/local/bin/procs
            cat > /etc/profile.d/procs-alias.sh <<'EOF'
alias ps='procs'
EOF
            chmod 644 /etc/profile.d/procs-alias.sh
            print_success "Procs installed (alias: ps)"
        else
            # Try finding any procs file
            binpath=$(find "$tmpdir" -type f -name 'procs*' -print -quit 2>/dev/null || true)
            if [ -n "$binpath" ]; then
                install -m 755 "$binpath" /usr/local/bin/procs
                print_success "Procs installed (alias: ps)"
            else
                print_error "Procs binary not found in archive"
            fi
        fi
    else
        print_error "Failed to extract Procs archive"
    fi
    rm -rf "$tmpdir" /tmp/procs.zip
}

install_tldr() {
    if [ "$GITHUB_ALLOWED" -eq 0 ]; then
        print_warning "IPv6-only detected: skipping Tldr (GitHub download required)."
        return
    fi
    if command_exists tldr; then
        print_info "Tldr already installed, skipping."
        return
    fi
    print_info "Installing Tldr (tlrc)..."
    # Get latest release tarball from tldr-pages/tlrc
    url=$(curl -sL --max-time 10 https://api.github.com/repos/tldr-pages/tlrc/releases/latest 2>/dev/null | grep -m1 '"browser_download_url".*x86_64-unknown-linux-musl\.tar\.gz"' | cut -d'"' -f4 || true)
    if [ -z "$url" ]; then print_error "Failed to fetch Tldr release"; return; fi
    wget -q "$url" -O /tmp/tlrc.tar.gz
    tmpdir=$(mktemp -d)
    if tar -xzf /tmp/tlrc.tar.gz -C "$tmpdir" 2>/dev/null; then
        binpath=$(find "$tmpdir" -type f -name tldr -executable -print -quit 2>/dev/null || true)
        if [ -n "$binpath" ]; then
            install -m 755 "$binpath" /usr/local/bin/tldr
            print_success "Tldr installed (use: tldr <command>)"
        else
            print_error "Tldr binary not found in archive"
        fi
    else
        print_error "Failed to extract Tldr archive"
    fi
    rm -rf "$tmpdir" /tmp/tlrc.tar.gz
}

install_zoxide() {
    if [ "$GITHUB_ALLOWED" -eq 0 ]; then
        print_warning "IPv6-only detected: skipping Zoxide (GitHub download required)."
        return
    fi
    if command_exists zoxide; then
        print_info "Zoxide already installed, skipping."
        return
    fi
    print_info "Installing Zoxide..."
    # Get latest release tarball
    url=$(curl -s --max-time 10 https://api.github.com/repos/ajeetdsouza/zoxide/releases/latest 2>/dev/null | grep -m1 '"browser_download_url".*zoxide-.*-x86_64-unknown-linux-musl\.tar\.gz"' | cut -d'"' -f4 || true)
    if [ -z "$url" ]; then print_error "Failed to fetch Zoxide release"; return; fi
    wget -q "$url" -O /tmp/zoxide.tar.gz
    tmpdir=$(mktemp -d)
    if tar -xzf /tmp/zoxide.tar.gz -C "$tmpdir" 2>/dev/null; then
        binpath=$(find "$tmpdir" -type f -name zoxide -executable -print -quit 2>/dev/null || true)
        if [ -n "$binpath" ]; then
            install -m 755 "$binpath" /usr/local/bin/zoxide
            # Add zoxide init to profile
            cat > /etc/profile.d/zoxide-init.sh <<'EOF'
# Zoxide init for bash
if command -v zoxide >/dev/null 2>&1; then
    eval "$(zoxide init bash)"
    alias cd='z'
fi
EOF
            chmod 644 /etc/profile.d/zoxide-init.sh
            print_success "Zoxide installed (alias: cd → z, use: z <dir>)"
        else
            print_error "Zoxide binary not found in archive"
        fi
    else
        print_error "Failed to extract Zoxide archive"
    fi
    rm -rf "$tmpdir" /tmp/zoxide.tar.gz
}

install_gping() {
    if [ "$GITHUB_ALLOWED" -eq 0 ]; then
        print_warning "IPv6-only detected: skipping Gping (GitHub download required)."
        return
    fi
    if command_exists gping; then
        print_info "Gping already installed, skipping."
        return
    fi
    print_info "Installing Gping..."
    # Get latest release tarball - correct filename pattern: gping-Linux-musl-x86_64.tar.gz
    url=$(curl -s --max-time 10 https://api.github.com/repos/orf/gping/releases/latest 2>/dev/null | grep -m1 '"browser_download_url".*gping-Linux-musl-x86_64\.tar\.gz"' | cut -d'"' -f4 || true)
    if [ -z "$url" ]; then print_error "Failed to fetch Gping release"; return; fi
    wget -q "$url" -O /tmp/gping.tar.gz
    tmpdir=$(mktemp -d)
    if tar -xzf /tmp/gping.tar.gz -C "$tmpdir" 2>/dev/null; then
        binpath=$(find "$tmpdir" -type f -name gping -executable -print -quit 2>/dev/null || true)
        if [ -n "$binpath" ]; then
            install -m 755 "$binpath" /usr/local/bin/gping
            print_success "Gping installed (use: gping <host>)"
        else
            print_error "Gping binary not found in archive"
        fi
    else
        print_error "Failed to extract Gping archive"
    fi
    rm -rf "$tmpdir" /tmp/gping.tar.gz
}

install_nexttrace_prompt() {
    if [ "$GITHUB_ALLOWED" -eq 0 ]; then
        print_warning "IPv6-only detected: skipping Nexttrace (GitHub download required)."
        return
    fi
    if command_exists nexttrace; then
        current_ver=$(nexttrace --version 2>/dev/null | head -n1 || echo "installed")
        echo -ne "${BOLD}Nexttrace already installed (${current_ver}). Reinstall/update? [y/N]: ${RESET}"
        read -r ans
        ans=${ans:-n}
        if [[ ! "$ans" =~ ^[Yy]$ ]]; then
            print_info "Keeping existing Nexttrace installation."
            return
        fi
    else
        echo -ne "${BOLD}Install Nexttrace (network trace tool, alias: nt)? [y/N]: ${RESET}"
        read -r ans
        ans=${ans:-n}
        if [[ ! "$ans" =~ ^[Yy]$ ]]; then
            print_info "Skipping Nexttrace installation."
            return
        fi
    fi
    print_info "Installing Nexttrace..."
    # Get latest release binary
    url=$(curl -s --max-time 10 https://api.github.com/repos/nxtrace/NTrace-core/releases/latest 2>/dev/null | grep -m1 '"browser_download_url".*nexttrace_linux_amd64"' | cut -d'"' -f4 || true)
    if [ -z "$url" ]; then print_error "Failed to fetch Nexttrace release"; return; fi
    wget -q "$url" -O /tmp/nexttrace
    if [ -s /tmp/nexttrace ]; then
        install -m 755 /tmp/nexttrace /usr/local/bin/nexttrace
        # Create nt alias
        cat > /etc/profile.d/nexttrace-alias.sh <<'EOF'
alias nt='nexttrace'
EOF
        chmod 644 /etc/profile.d/nexttrace-alias.sh
        print_success "Nexttrace installed (alias: nt)"
    else
        print_error "Failed to download Nexttrace"
    fi
    rm -f /tmp/nexttrace
}

install_missing_tools() {
    print_banner "${ICON_TOOL} Tools setup"
    install_eza
    install_helix
    install_speedtest
    install_duf
    install_bat
    install_btop
    install_fd
    install_procs
    install_tldr
    install_zoxide
    install_gping
}

configure_unattended() {
    local codename_regex
    codename_regex="(${DISTRO_CODENAME}|\\\${distro_codename})"
    if ! command_exists unattended-upgrade; then
        echo -ne "${BOLD}Auto-update mode: 1) security-only 2) security + stable updates [1/2, default 1]: ${RESET}"
        read -r upd_choice
        upd_choice=${upd_choice:-1}
        install_unattended
        cp /etc/apt/apt.conf.d/50unattended-upgrades /etc/apt/apt.conf.d/52unattended-upgrades-local
        if [ "$upd_choice" = "2" ]; then
            sed -i "s|^//\\( *\"origin=Debian,codename=\\\${distro_codename}-updates\";\\)|\\1|" /etc/apt/apt.conf.d/52unattended-upgrades-local
            print_success "Enabled automatic security + stable updates"
        else
            print_success "Enabled automatic security updates (default)"
        fi
        systemctl enable --now apt-daily.timer apt-daily-upgrade.timer 2>/dev/null || true
        return
    fi

    # Already installed: check whether stable updates are enabled
    cfg=""
    if [ -f /etc/apt/apt.conf.d/52unattended-upgrades-local ]; then
        cfg="/etc/apt/apt.conf.d/52unattended-upgrades-local"
    elif [ -f /etc/apt/apt.conf.d/50unattended-upgrades ]; then
        cfg="/etc/apt/apt.conf.d/50unattended-upgrades"
    fi

    stable_enabled="no"
    security_enabled="no"
    if [ -n "$cfg" ]; then
        grep -qE "^\s*\"origin=Debian,codename=${codename_regex}-security" "$cfg" 2>/dev/null && security_enabled="yes"
        grep -qE "^\s*\"origin=Debian,codename=${codename_regex}-updates" "$cfg" 2>/dev/null && stable_enabled="yes"
    fi

    if [ "$stable_enabled" = "yes" ]; then
        print_info "unattended-upgrades already set to security + stable updates; keeping as-is."
        systemctl enable --now apt-daily.timer apt-daily-upgrade.timer 2>/dev/null || true
        return
    fi

    if [ "$security_enabled" = "yes" ]; then
        echo -ne "${BOLD}Currently security-only. Enable stable updates too? [y/N]: ${RESET}"
        read -r add_stable
        add_stable=${add_stable:-n}
        if [[ "$add_stable" =~ ^[Yy]$ ]]; then
            [ -z "$cfg" ] && cfg="/etc/apt/apt.conf.d/52unattended-upgrades-local"
            [ ! -f "$cfg" ] && cp /etc/apt/apt.conf.d/50unattended-upgrades "$cfg"
            sed -i "s|^//\\( *\"origin=Debian,codename=\\\${distro_codename}-updates\";\\)|\\1|" "$cfg"
            systemctl enable --now apt-daily.timer apt-daily-upgrade.timer 2>/dev/null || true
            print_success "Stable updates enabled (security remains enabled)"
        else
            print_info "Keeping security-only updates."
        fi
    else
        print_warning "Security updates entry not detected; please review configuration."
    fi
}

install_docker_prompt() {
    if command_exists docker; then
        current_ver=$(docker --version 2>/dev/null | head -n1 || echo "installed")
        echo -ne "${BOLD}Docker already detected (${current_ver}). Reinstall/update via get.docker.com? [y/N]: ${RESET}"
        read -r ans
        ans=${ans:-n}
        if [[ ! "$ans" =~ ^[Yy]$ ]]; then
            print_info "Keeping existing Docker installation."
            return
        fi
    else
        echo -ne "${BOLD}Install Docker? [y/N]: ${RESET}"
        read -r ans
        ans=${ans:-n}
        if [[ ! "$ans" =~ ^[Yy]$ ]]; then
            print_info "Skipping Docker installation"
            return
        fi
    fi
    print_info "Installing Docker..."
    wget -qO- https://get.docker.com/ | sh
    print_success "Docker installation finished"
}

install_base_packages() {
    print_banner "${ICON_PKG} Installing base packages"
    apt-get install $APT_INSTALL_OPTS openssl gnupg curl wget nano cron chrony fail2ban unzip logrotate vnstat nload
    systemctl enable --now fail2ban 2>/dev/null || true
    print_success "Base packages installed"
}

configure_chrony() {
    print_banner "${ICON_TIME} Time sync & timezone"
    # Choose NTP pool based on IP
    region_prefix=""
    case "${IP_TZ:-}" in
        Asia/*) region_prefix="asia." ;;
        Europe/*) region_prefix="europe." ;;
        Africa/*) region_prefix="africa." ;;
        Australia/*|Pacific/*) region_prefix="oceania." ;;
        America/*)
            if [[ "${IP_TZ:-}" =~ (Argentina|Brazil|Chile|Colombia|Peru|Venezuela|Sao_Paulo|Buenos_Aires|Santiago|Bogota|Lima|Caracas) ]]; then
                region_prefix="south-america."
            else
                region_prefix="north-america."
            fi
            ;;
        *) region_prefix="" ;;
    esac
    CHRONY_CONF="/etc/chrony/chrony.conf"
    mkdir -p /etc/chrony
    if [ -f "$CHRONY_CONF" ]; then
        cp "$CHRONY_CONF" "${CHRONY_CONF}.bak"
    fi
    cat > "$CHRONY_CONF" <<EOF
server 0.${region_prefix}pool.ntp.org iburst
server 1.${region_prefix}pool.ntp.org iburst
server 2.${region_prefix}pool.ntp.org iburst
server 3.${region_prefix}pool.ntp.org iburst
driftfile /var/lib/chrony/chrony.drift
makestep 1.0 3
rtcsync
log tracking measurements statistics
logdir /var/log/chrony
EOF
    systemctl enable --now chrony 2>/dev/null || true
    print_success "chrony configured (${region_prefix:-global} pool)"

    CURRENT_TZ=$(timedatectl show --property=Timezone --value 2>/dev/null || echo "Unknown")
    print_kv "Current timezone" "$CURRENT_TZ"
    print_kv "Suggested timezone" "${IP_TZ:-Unknown}"
    echo ""
    
    # Timezone selection: suggested, custom, or keep current
    if [ -n "${IP_TZ:-}" ] && [ "$IP_TZ" != "$CURRENT_TZ" ]; then
        echo -e " ${BLUE}1)${RESET} Use suggested: ${IP_TZ}"
        echo -e " ${BLUE}2)${RESET} Enter custom timezone"
        echo -e " ${BLUE}3)${RESET} Keep current: ${CURRENT_TZ}"
        echo -ne "${BOLD}Choose [1/2/3, default 1]: ${RESET}"
        read -r tz_choice
        tz_choice=${tz_choice:-1}
        
        case "$tz_choice" in
            1)
                if timedatectl set-timezone "$IP_TZ" 2>/dev/null; then
                    print_success "Timezone set to $IP_TZ"
                    CURRENT_TZ="$IP_TZ"
                else
                    print_error "Failed to set timezone; keeping current."
                fi
                ;;
            2)
                echo -ne "${BOLD}Enter timezone (e.g., Asia/Shanghai): ${RESET}"
                read -r newtz
                if [ -n "$newtz" ]; then
                    if timedatectl set-timezone "$newtz" 2>/dev/null; then
                        print_success "Timezone set to $newtz"
                        CURRENT_TZ="$newtz"
                    else
                        print_error "Invalid timezone; keeping current."
                    fi
                else
                    print_info "Keeping current timezone: $CURRENT_TZ"
                fi
                ;;
            *)
                print_info "Keeping current timezone: $CURRENT_TZ"
                ;;
        esac
    else
        print_info "Timezone already matches suggested or no suggestion available."
    fi
    TIMEZONE_FINAL="$CURRENT_TZ"
}

prompt_forwarding() {
    local current_fwd
    current_fwd=$(sysctl -n net.ipv4.ip_forward 2>/dev/null || echo "0")
    echo ""
    if [ "$current_fwd" = "1" ]; then
        # Currently enabled, ask if user wants to disable (default: keep enabled)
        echo -ne "${BOLD}IP forwarding is currently enabled. Keep enabled? [Y/n]: ${RESET}"
        read -r ans
        ans=${ans:-y}
        if [[ "$ans" =~ ^[Nn]$ ]]; then
            ENABLE_FORWARDING=0
            print_info "IP forwarding will be disabled."
        else
            ENABLE_FORWARDING=1
            print_info "Keeping IP forwarding enabled."
        fi
    else
        # Currently disabled, ask if user wants to enable (default: keep disabled)
        echo -ne "${BOLD}Enable IPv4/IPv6 forwarding (turns host into a router)? [y/N]: ${RESET}"
        read -r ans
        if [[ "$ans" =~ ^[Yy]$ ]]; then
            ENABLE_FORWARDING=1
            print_info "IP forwarding will be enabled."
        else
            ENABLE_FORWARDING=0
        fi
    fi
}

prompt_disable_ipv6() {
    # Check if IPv6 is currently enabled
    local ipv6_disabled
    ipv6_disabled=$(sysctl -n net.ipv6.conf.all.disable_ipv6 2>/dev/null || echo "0")
    if [ "$ipv6_disabled" = "1" ]; then
        # Currently disabled, ask if user wants to enable (default: keep disabled)
        echo ""
        echo -ne "${BOLD}IPv6 is currently disabled. Keep disabled? [Y/n]: ${RESET}"
        read -r ans
        ans=${ans:-y}
        if [[ "$ans" =~ ^[Nn]$ ]]; then
            DISABLE_IPV6=0
            print_info "IPv6 will be enabled."
        else
            DISABLE_IPV6=1
            print_info "Keeping IPv6 disabled."
        fi
    else
        # Currently enabled, ask if user wants to disable (default: keep enabled)
        echo ""
        echo -ne "${BOLD}IPv6 is currently enabled. Disable IPv6? [y/N]: ${RESET}"
        read -r ans
        if [[ "$ans" =~ ^[Yy]$ ]]; then
            DISABLE_IPV6=1
            print_info "IPv6 will be disabled."
        else
            DISABLE_IPV6=0
        fi
    fi
}

is_sysctl_supported() {
    local key="$1"
    local path="/proc/sys/${key//./\/}"
    [ -e "$path" ]
}

filter_sysctl_file() {
    local src="$1" dest="$2" unsupported=0
    while IFS= read -r line; do
        # Preserve comments and blank lines
        if [[ -z "${line// }" || "$line" =~ ^[[:space:]]*# ]]; then
            echo "$line" >>"$dest"
            continue
        fi
        local key val
        key=$(echo "$line" | cut -d= -f1 | xargs)
        val=$(echo "$line" | cut -d= -f2- | sed 's/^ *//')
        if is_sysctl_supported "$key"; then
            echo "$key = $val" >>"$dest"
        else
            echo "# skipped (unsupported): $key = $val" >>"$dest"
            unsupported=1
        fi
    done <"$src"
    if [ "$unsupported" -eq 1 ]; then
        print_warning "Some sysctl keys not supported on this kernel; they were commented out in $dest"
    fi
}

generate_sysctl_content() {
    cat <<SYSCTL
# ============================================================================
# Generated by: debian_init.sh
# Do not edit manually - changes may be overwritten
# ============================================================================

# ============================================================================
# BBR + TCP Congestion Control
# ============================================================================
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr

# ============================================================================
# TCP Buffer Optimization
# ============================================================================
net.core.rmem_default = 262144
net.core.wmem_default = 262144
net.core.rmem_max = 67108864
net.core.wmem_max = 67108864
net.core.optmem_max = 65536

net.ipv4.tcp_rmem = 4096 87380 33554432
net.ipv4.tcp_wmem = 4096 65536 33554432

# ============================================================================
# TCP Performance Tuning
# ============================================================================
net.core.somaxconn = 8192
net.core.netdev_max_backlog = 16384
net.ipv4.tcp_max_syn_backlog = 8192
net.ipv4.tcp_max_tw_buckets = 65536

net.ipv4.tcp_fastopen = 3
net.ipv4.tcp_mtu_probing = 1
net.ipv4.tcp_sack = 1
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_slow_start_after_idle = 0
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 15
net.ipv4.tcp_keepalive_time = 600
net.ipv4.tcp_keepalive_intvl = 15
net.ipv4.tcp_keepalive_probes = 5
net.ipv4.tcp_notsent_lowat = 16384
net.ipv4.ip_local_port_range = 1024 65535

# ============================================================================
# Security Hardening
# ============================================================================
# SYN flood protection
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_rfc1337 = 1

# Reverse path filtering (anti-spoofing)
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1

# Ignore ICMP broadcasts (prevent Smurf attacks)
net.ipv4.icmp_echo_ignore_broadcasts = 1
net.ipv4.icmp_ignore_bogus_error_responses = 1

# Disable ICMP redirects (prevent MITM)
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0

# Disable source routing
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
net.ipv6.conf.all.accept_source_route = 0
net.ipv6.conf.default.accept_source_route = 0

# ============================================================================
# File System & Memory
# ============================================================================
fs.file-max = 2097152
vm.dirty_ratio = 10
vm.dirty_background_ratio = 5
SYSCTL
}

apply_network_sysctl() {
    print_banner "${ICON_GEAR} Network tuning"
    
    # Backup other (non-script) sysctl configs before applying ours
    backup_other_sysctl
    
    local tmpfile
    tmpfile=$(mktemp)
    
    generate_sysctl_content > "$tmpfile"
    
    mkdir -p /etc/sysctl.d
    backup_file "$SYSCTL_NETWORK_FILE" "$(cat "$tmpfile")"
    : > "$SYSCTL_NETWORK_FILE"
    filter_sysctl_file "$tmpfile" "$SYSCTL_NETWORK_FILE"
    rm -f "$tmpfile"
    
    print_success "Network tuning config written to $SYSCTL_NETWORK_FILE"
}

apply_swappiness_sysctl() {
    local swappiness
    mkdir -p /etc/sysctl.d
    
    # Determine swappiness based on swap type
    # zram is fast (in-memory), so higher swappiness is beneficial
    # Disk swap is slow, so lower swappiness is preferred
    if grep -q "^/dev/zram" /proc/swaps 2>/dev/null; then
        swappiness=60
        print_info "zram detected: using swappiness=60"
    else
        swappiness=10
        print_info "No zram: using swappiness=10"
    fi
    
    local new_content
    new_content="vm.swappiness = ${swappiness}"
    backup_file "$SYSCTL_SWAPPINESS_FILE" "$new_content"
    cat > "$SYSCTL_SWAPPINESS_FILE" <<EOF
# ============================================================================
# Generated by: debian_init.sh
# Do not edit manually - changes may be overwritten
# ============================================================================

# Swappiness - auto-configured based on swap type
# zram (fast, in-memory): 60
# Disk swap (slow): 10
vm.swappiness = ${swappiness}
EOF
    
    print_success "Swappiness config written to $SYSCTL_SWAPPINESS_FILE"
}

apply_forwarding_sysctl() {
    mkdir -p /etc/sysctl.d
    if [ "$ENABLE_FORWARDING" -eq 1 ]; then
        local new_content="net.ipv4.ip_forward = 1
net.ipv6.conf.all.forwarding = 1
net.ipv6.conf.default.forwarding = 1"
        backup_file "$SYSCTL_FORWARDING_FILE" "$new_content"
        cat > "$SYSCTL_FORWARDING_FILE" <<'EOF'
# ============================================================================
# Generated by: debian_init.sh
# Do not edit manually - changes may be overwritten
# ============================================================================

# IP forwarding - enables routing between interfaces
net.ipv4.ip_forward = 1
net.ipv6.conf.all.forwarding = 1
net.ipv6.conf.default.forwarding = 1
EOF
        print_success "IP forwarding enabled ($SYSCTL_FORWARDING_FILE)"
    else
        # Disable forwarding immediately (kernel defaults to 0)
        sysctl -w net.ipv4.ip_forward=0 >/dev/null 2>&1 || true
        sysctl -w net.ipv6.conf.all.forwarding=0 >/dev/null 2>&1 || true
        sysctl -w net.ipv6.conf.default.forwarding=0 >/dev/null 2>&1 || true
        # Remove forwarding config if exists
        if [ -f "$SYSCTL_FORWARDING_FILE" ]; then
            backup_file "$SYSCTL_FORWARDING_FILE"
            rm -f "$SYSCTL_FORWARDING_FILE"
        fi
        print_success "IP forwarding disabled"
    fi
}

apply_ipv6_sysctl() {
    mkdir -p /etc/sysctl.d
    if [ "$DISABLE_IPV6" -eq 1 ]; then
        local new_content="net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1"
        backup_file "$SYSCTL_IPV6_FILE" "$new_content"
        cat > "$SYSCTL_IPV6_FILE" <<'EOF'
# ============================================================================
# Generated by: debian_init.sh
# Do not edit manually - changes may be overwritten
# ============================================================================

# Disable IPv6 completely
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
EOF
        print_success "IPv6 disabled ($SYSCTL_IPV6_FILE)"
    else
        # Enable IPv6 immediately (kernel defaults to 0 = enabled)
        sysctl -w net.ipv6.conf.all.disable_ipv6=0 >/dev/null 2>&1 || true
        sysctl -w net.ipv6.conf.default.disable_ipv6=0 >/dev/null 2>&1 || true
        sysctl -w net.ipv6.conf.lo.disable_ipv6=0 >/dev/null 2>&1 || true
        # Remove IPv6 disable config if exists
        if [ -f "$SYSCTL_IPV6_FILE" ]; then
            backup_file "$SYSCTL_IPV6_FILE"
            rm -f "$SYSCTL_IPV6_FILE"
        fi
        print_success "IPv6 enabled"
    fi
}

apply_all_sysctl() {
    sysctl --system >/dev/null 2>&1 || true
    BBR_APPLIED=$(sysctl -n net.ipv4.tcp_congestion_control 2>/dev/null || echo "unknown")
    QDISC_APPLIED=$(sysctl -n net.core.default_qdisc 2>/dev/null || echo "unknown")
    print_success "sysctl applied (BBR: $BBR_APPLIED, qdisc: $QDISC_APPLIED)"
}

get_recommended_zram_percent() {
    # Calculate recommended zram percentage based on RAM size
    # Smaller RAM needs higher percentage to have usable swap
    local mem_mb=$1
    if [ "$mem_mb" -le 512 ]; then
        echo 150   # 512MB RAM → 768MB zram (compression makes it ~1.5-3GB effective)
    elif [ "$mem_mb" -le 1024 ]; then
        echo 100   # 1GB RAM → 1GB zram
    elif [ "$mem_mb" -le 2048 ]; then
        echo 75    # 2GB RAM → 1.5GB zram
    elif [ "$mem_mb" -le 4096 ]; then
        echo 50    # 4GB RAM → 2GB zram
    else
        echo 25    # 8GB+ RAM → 25% is enough
    fi
}

configure_zram() {
    local percent="$1"
    local mem_mb="$2"
    local zram_size_mb=$((mem_mb * percent / 100))
    
    # Ensure zram-tools is installed
    if ! dpkg -l zram-tools 2>/dev/null | grep -q "^ii"; then
        print_info "Installing zram-tools..."
        apt-get install $APT_INSTALL_OPTS zram-tools
    fi
    
    # Stop service first
    systemctl stop zramswap.service 2>/dev/null || true
    
    # Write configuration
    cat > /etc/default/zramswap <<EOF
# zramswap config managed by init script
ALGO=lz4
PERCENT=${percent}
PRIORITY=100
EOF
    
    # Start with new config
    systemctl enable --now zramswap.service 2>/dev/null || true
    
    print_success "zram configured: ${percent}% of RAM (~${zram_size_mb}MB, lz4 compressed)"
}

maybe_enable_zram_swap() {
    local has_zram=0 has_disk_swap=0 disk_swap_info=""
    local mem_mb current_zram_mb current_percent recommended_percent
    
    mem_mb=$((MEM_KB / 1024))
    recommended_percent=$(get_recommended_zram_percent "$mem_mb")
    local recommended_size_mb=$((mem_mb * recommended_percent / 100))
    
    # Check current swap status
    if grep -q "^/dev/zram" /proc/swaps 2>/dev/null; then
        has_zram=1
        current_zram_mb=$(awk '$1 ~ /zram/ {s+=$3} END {printf "%.0f", s/1024}' /proc/swaps)
    fi
    # Check for non-zram swap (disk partition or swap file)
    if awk 'NR>1 && $1 !~ /zram/ {found=1} END {exit !found}' /proc/swaps 2>/dev/null; then
        has_disk_swap=1
        disk_swap_info=$(awk 'NR>1 && $1 !~ /zram/ {printf "%s (%d MB) ", $1, $3/1024}' /proc/swaps)
    fi
    
    # Case 1: Already has zram → offer to adjust size
    if [ "$has_zram" -eq 1 ]; then
        current_percent=$((current_zram_mb * 100 / mem_mb))
        print_info "zram swap active: ${current_zram_mb}MB (~${current_percent}% of RAM)"
        print_info "Recommended for ${mem_mb}MB RAM: ${recommended_percent}% (~${recommended_size_mb}MB)"
        
        # Only offer change if current differs significantly from recommended
        local diff=$((current_percent - recommended_percent))
        [ "$diff" -lt 0 ] && diff=$((-diff))
        
        if [ "$diff" -ge 15 ]; then
            echo -ne "${BOLD}Adjust zram to recommended ${recommended_percent}%? [y/N]: ${RESET}"
            read -r ans
            if [[ "$ans" =~ ^[Yy]$ ]]; then
                configure_zram "$recommended_percent" "$mem_mb"
            else
                print_info "Keeping current zram configuration."
            fi
        else
            print_info "Current zram size is reasonable; no change needed."
        fi
        return
    fi
    
    # Case 2: Has disk swap but no zram → offer to add zram (coexist)
    if [ "$has_disk_swap" -eq 1 ]; then
        print_info "Disk swap detected: ${disk_swap_info}"
        print_info "Recommended zram for ${mem_mb}MB RAM: ${recommended_percent}% (~${recommended_size_mb}MB)"
        echo -ne "${BOLD}Add zram swap alongside disk swap? (zram will be used first, priority=100) [y/N]: ${RESET}"
        read -r ans
        if [[ ! "$ans" =~ ^[Yy]$ ]]; then
            print_info "Keeping disk swap only."
            return
        fi
        configure_zram "$recommended_percent" "$mem_mb"
        print_info "zram coexists with disk swap (zram priority=100, used first)"
        return
    fi
    
    # Case 3: No swap at all → offer zram
    print_info "No swap detected."
    print_info "Recommended zram for ${mem_mb}MB RAM: ${recommended_percent}% (~${recommended_size_mb}MB)"
    echo -ne "${BOLD}Enable zram swap? [y/N]: ${RESET}"
    read -r ans
    if [[ ! "$ans" =~ ^[Yy]$ ]]; then
        print_info "Skipping zram swap setup."
        return
    fi
    configure_zram "$recommended_percent" "$mem_mb"
}

backup_other_sysctl() {
    # Backup non-script-generated sysctl configs to a timestamped folder
    # This disables them (by moving out of sysctl.d) while preserving for reference
    if [ -z "$OTHER_SYSCTL_FILES" ]; then
        return
    fi
    
    local backup_dir="/etc/sysctl.d/bak-utc-${SCRIPT_TIMESTAMP}"
    local backed_up=0
    
    for f in $OTHER_SYSCTL_FILES; do
        [ -f "$f" ] || continue
        
        # Create backup directory if needed
        if [ "$backed_up" -eq 0 ]; then
            mkdir -p "$backup_dir"
            print_info "Backing up existing sysctl configs to $backup_dir"
        fi
        
        local basename
        basename=$(basename "$f")
        
        if [ "$f" = "/etc/sysctl.conf" ]; then
            # Special handling for /etc/sysctl.conf - copy and clear
            cp "$f" "${backup_dir}/sysctl.conf.bak"
            # Clear the file but keep it (some systems expect it to exist)
            cat > "$f" <<EOF
# Cleared by debian_init.sh on ${SCRIPT_TIMESTAMP} UTC
# Original backed up to: ${backup_dir}/sysctl.conf.bak
EOF
            echo -e "  ${YELLOW}•${RESET} /etc/sysctl.conf → ${backup_dir}/sysctl.conf.bak (cleared)"
        else
            # Move .conf files to backup dir with .bak extension
            mv "$f" "${backup_dir}/${basename}.bak"
            echo -e "  ${YELLOW}•${RESET} $f → ${backup_dir}/${basename}.bak"
        fi
        backed_up=$((backed_up + 1))
    done
    
    if [ "$backed_up" -gt 0 ]; then
        print_success "Backed up $backed_up config(s) - old settings disabled"
    fi
}

write_marker() {
    mkdir -p "$(dirname "$MARKER_FILE")"
    {
        echo "# Marker for debian_init.sh"
        echo "# Indicates 99-network-tuning.conf has been applied"
        echo "timestamp_utc: ${SCRIPT_TIMESTAMP}"
    } > "$MARKER_FILE"
    print_info "Marker written to: $MARKER_FILE"
}

show_report() {
    print_banner "${ICON_DOC} Summary"
    print_kv "BBR" "$(sysctl -n net.ipv4.tcp_congestion_control 2>/dev/null || echo '?')"
    print_kv "Queueing" "$(sysctl -n net.core.default_qdisc 2>/dev/null || echo '?')"
    print_kv "swappiness" "$(sysctl -n vm.swappiness 2>/dev/null || echo '?')"
    print_kv "IP forwarding" "$(sysctl -n net.ipv4.ip_forward 2>/dev/null | grep -q 1 && echo 'enabled' || echo 'disabled')"
    print_kv "IPv6" "$(sysctl -n net.ipv6.conf.all.disable_ipv6 2>/dev/null | grep -q 1 && echo 'disabled' || echo 'enabled')"
    echo ""
    print_info "sysctl configs:"
    [ -f "$SYSCTL_NETWORK_FILE" ] && echo -e "  ${GREEN}•${RESET} $SYSCTL_NETWORK_FILE"
    [ -f "$SYSCTL_SWAPPINESS_FILE" ] && echo -e "  ${GREEN}•${RESET} $SYSCTL_SWAPPINESS_FILE"
    [ -f "$SYSCTL_FORWARDING_FILE" ] && echo -e "  ${GREEN}•${RESET} $SYSCTL_FORWARDING_FILE"
    [ -f "$SYSCTL_IPV6_FILE" ] && echo -e "  ${GREEN}•${RESET} $SYSCTL_IPV6_FILE"
    echo ""
    print_info "Modern CLI tools:"
    [ "$EZA_VER" != "Not installed" ] && print_kv "  Eza" "$EZA_VER (ls, ll, la, lt)" || print_kv "  Eza" "$EZA_VER"
    [ "$HELIX_VER" != "Not installed" ] && print_kv "  Helix" "$HELIX_VER (vi, vim, hx)" || print_kv "  Helix" "$HELIX_VER"
    [ "$BAT_VER" != "Not installed" ] && print_kv "  Bat" "$BAT_VER (cat, less)" || print_kv "  Bat" "$BAT_VER"
    [ "$BTOP_VER" != "Not installed" ] && print_kv "  Btop" "$BTOP_VER (htop, top)" || print_kv "  Btop" "$BTOP_VER"
    [ "$DUF_VER" != "Not installed" ] && print_kv "  Duf" "$DUF_VER (df)" || print_kv "  Duf" "$DUF_VER"
    [ "$FD_VER" != "Not installed" ] && print_kv "  Fd" "$FD_VER (find)" || print_kv "  Fd" "$FD_VER"
    [ "$PROCS_VER" != "Not installed" ] && print_kv "  Procs" "$PROCS_VER (ps)" || print_kv "  Procs" "$PROCS_VER"
    [ "$TLDR_VER" != "Not installed" ] && print_kv "  Tldr" "$TLDR_VER (tldr <cmd>)" || print_kv "  Tldr" "$TLDR_VER"
    [ "$ZOXIDE_VER" != "Not installed" ] && print_kv "  Zoxide" "$ZOXIDE_VER (cd → z)" || print_kv "  Zoxide" "$ZOXIDE_VER"
    [ "$GPING_VER" != "Not installed" ] && print_kv "  Gping" "$GPING_VER (gping <host>)" || print_kv "  Gping" "$GPING_VER"
    [ "$SPEEDTEST_VER" != "Not installed" ] && print_kv "  Speedtest" "$SPEEDTEST_VER" || print_kv "  Speedtest" "$SPEEDTEST_VER"
    echo ""
    [ "$NEXTTRACE_VER" != "Not installed" ] && print_kv "Nexttrace" "$NEXTTRACE_VER (nt)" || print_kv "Nexttrace" "$NEXTTRACE_VER"
    print_kv "chrony" "$(systemctl is-active chrony 2>/dev/null || echo '?')"
    print_kv "fail2ban" "$(systemctl is-active fail2ban 2>/dev/null || echo '?')"
    if command_exists unattended-upgrade; then
        print_kv "unattended-upgrades" "installed ($(systemctl is-active apt-daily-upgrade.timer 2>/dev/null || echo 'timer?'))"
    else
        print_kv "unattended-upgrades" "not installed"
    fi
    print_kv "zram swap" "${ZRAM_STATUS:-not detected}"
    print_kv "Docker" "$DOCKER_STATUS"
    print_kv "Timezone" "${TIMEZONE_FINAL:-unknown}"
    print_kv "Marker" "$MARKER_FILE"
    echo ""
    print_success "All steps complete. Reboot recommended for full effect."
    echo ""
    # Try to activate aliases in current shell
    source /etc/profile 2>/dev/null || true
    print_info "Aliases should be activated. If not, run:"
    echo -e "   ${CYAN}source /etc/profile${RESET}"
}

show_tools_summary() {
    print_banner "${ICON_DOC} Summary (re-run mode)"
    print_info "Modern CLI tools:"
    [ "$EZA_VER" != "Not installed" ] && print_kv "  Eza" "$EZA_VER (ls, ll, la, lt)" || print_kv "  Eza" "$EZA_VER"
    [ "$HELIX_VER" != "Not installed" ] && print_kv "  Helix" "$HELIX_VER (vi, vim, hx)" || print_kv "  Helix" "$HELIX_VER"
    [ "$BAT_VER" != "Not installed" ] && print_kv "  Bat" "$BAT_VER (cat, less)" || print_kv "  Bat" "$BAT_VER"
    [ "$BTOP_VER" != "Not installed" ] && print_kv "  Btop" "$BTOP_VER (htop, top)" || print_kv "  Btop" "$BTOP_VER"
    [ "$DUF_VER" != "Not installed" ] && print_kv "  Duf" "$DUF_VER (df)" || print_kv "  Duf" "$DUF_VER"
    [ "$FD_VER" != "Not installed" ] && print_kv "  Fd" "$FD_VER (find)" || print_kv "  Fd" "$FD_VER"
    [ "$PROCS_VER" != "Not installed" ] && print_kv "  Procs" "$PROCS_VER (ps)" || print_kv "  Procs" "$PROCS_VER"
    [ "$TLDR_VER" != "Not installed" ] && print_kv "  Tldr" "$TLDR_VER (tldr <cmd>)" || print_kv "  Tldr" "$TLDR_VER"
    [ "$ZOXIDE_VER" != "Not installed" ] && print_kv "  Zoxide" "$ZOXIDE_VER (cd → z)" || print_kv "  Zoxide" "$ZOXIDE_VER"
    [ "$GPING_VER" != "Not installed" ] && print_kv "  Gping" "$GPING_VER (gping <host>)" || print_kv "  Gping" "$GPING_VER"
    [ "$SPEEDTEST_VER" != "Not installed" ] && print_kv "  Speedtest" "$SPEEDTEST_VER" || print_kv "  Speedtest" "$SPEEDTEST_VER"
    echo ""
    [ "$NEXTTRACE_VER" != "Not installed" ] && print_kv "Nexttrace" "$NEXTTRACE_VER (nt)" || print_kv "Nexttrace" "$NEXTTRACE_VER"
    print_kv "zram swap" "${ZRAM_STATUS:-not detected}"
    print_kv "IP forwarding" "$(sysctl -n net.ipv4.ip_forward 2>/dev/null | grep -q 1 && echo 'enabled' || echo 'disabled')"
    print_kv "IPv6" "$(sysctl -n net.ipv6.conf.all.disable_ipv6 2>/dev/null | grep -q 1 && echo 'disabled' || echo 'enabled')"
    if command_exists docker; then
        print_kv "Docker" "installed"
    else
        print_kv "Docker" "not installed"
    fi
    echo ""
    print_success "Re-run mode finished (marker present)."
    # Try to activate aliases in current shell
    source /etc/profile 2>/dev/null || true
    print_info "Aliases should be activated. If not, run:"
    echo -e "   ${CYAN}source /etc/profile${RESET}"
}

main() {
    require_root
    require_debian
    ensure_basic_tools
    detect_existing_sysctl
    check_marker
    fetch_ipinfo
    detect_versions
    detect_updates_hint
    detect_unattended
    detect_system
    detect_docker_status
    detect_zram_status
    show_detection
    confirm_proceed
    if [ "$MODE_LITE" -eq 1 ]; then
        apt_refresh
        install_missing_tools
        configure_unattended
        install_docker_prompt
        install_nexttrace_prompt
        install_base_packages
        maybe_enable_zram_swap
        apply_swappiness_sysctl
        # Also allow configuring forwarding/ipv6 in re-run mode
        prompt_forwarding
        prompt_disable_ipv6
        apply_forwarding_sysctl
        apply_ipv6_sysctl
        apply_all_sysctl
        detect_docker_status
        detect_zram_status
        detect_versions
        show_tools_summary
        exit 0
    fi
    apt_refresh
    install_missing_tools
    install_docker_prompt
    install_nexttrace_prompt
    configure_unattended
    install_base_packages
    configure_chrony
    maybe_enable_zram_swap
    apply_swappiness_sysctl
    prompt_forwarding
    prompt_disable_ipv6
    apply_network_sysctl
    apply_forwarding_sysctl
    apply_ipv6_sysctl
    apply_all_sysctl
    detect_docker_status
    detect_zram_status
    detect_versions
    write_marker
    show_report
}

main "$@"
